insert into domain (id,name,code) values (1, 'Eclairage Public','EP');
insert into domain (id,name,code) values (2, 'Vidéoprotection et surveillance','VP');
insert into domain (id,name,code) values (3, 'Signalisation Lumineuse Tricolore ','SLT');
insert into domain (id,name,code) values (4, 'Réseaux télécoms','RT');
insert into domain (id,name,code) values (5, 'Patrimoine','PAT');
insert into domain (id,name,code) values (6, 'Stationnement et mobilité','MOB');
insert into domain (id,name,code) values (7, 'Cadre de vie','CDV');

insert into family (id,name,code) values (1,'Armoire','EP_ARMOIRE');
insert into family (id,name,code) values (2,'Foyer Lumineux','EP_FOYER_LUMINEUX');
insert into family (id,name,code) values (3,'Ouvrage','EP_OUVRAGE');
insert into family (id,name,code) values (4,'Camera','VP_CAM');

insert into category (id,name,code, parent_id) values (1,'Manifestation','MANIFESTATION',null);
insert into category (id,name,code, parent_id) values (2,'Hors Service','OUTOFORDER',null);
insert into category (id,name,code, parent_id) values (3,'Seuil','LIMIT',null);
insert into category (id,name,code, parent_id) values (4,'Anomalie','ANOMALY',null);
insert into category (id,name,code, parent_id) values (5,'Affluence anormal de personne','UNUSUAL_FLOW',4);
insert into category (id,name,code, parent_id) values (6,'Congestion de vehicule','TRAFFIC_CONGESTION',4);
insert into category (id,name,code, parent_id) values (7,'Dépôt Sauvage','WILD_STORAGE',4);

insert into service_category (id,name,code) values (1,'Préventive','PREV');
insert into service_category (id,name,code) values (2,'Curative','CURA');

insert into custom_action_type (id,name,code) values (1,'Appeler le CSU','CSU');
insert into custom_action_type (id,name,code) values (2,'Levée de doute','DOUTE');

insert into equipment_entity (id,code,name) values (1,'AGGLO-COMMUN', 'Châlons Agglomération');
insert into equipment_entity (id,code,name) values (2,'CHALONS-COMMUN', 'Châlons-en-Champagne');
insert into equipment_entity (id,code,name) values (3,'FAGNIERES-COMMUN', 'Fagnières');
insert into equipment_entity (id,code,name) values (4,'SAINT-MARTIN-COMMUN', 'St-Martin-sur-le-Pré');

insert into city (id,code,name) values (1,'CHALONS', 'Châlons en Champagne');
insert into city (id,code,name) values (2,'FAGNIERES', 'Fagnières');
insert into city (id,code,name) values (3,'ST-MARTIN', 'Saint Martin-sur-le-Pré');
insert into city (id,code,name) values (4,'CONDE', 'Condé');
insert into city (id,code,name) values (5,'MATOUGUES', 'Matougues');
insert into city (id,code,name) values (6,'MOURM-LG', 'Mourmelon le Grand');
insert into city (id,code,name) values (7,'BACONNES', 'Baconnes');
insert into city (id,code,name) values (8,'GRD-LOGES', 'Les Grandes Loges');
insert into city (id,code,name) values (9,'SARRY', 'Sarry');
insert into city (id,code,name) values (10,'ST-MEMMIE', 'Saint-Memmie');
insert into city (id,code,name) values (11,'RECY', 'Recy');
insert into city (id,code,name) values (12,'COMPERTRIX', 'Compertrix');
insert into city (id,code,name) values (13,'COOLUS', 'Coolus');
insert into city (id,code,name) values (14,'BUSSY-LETT', 'Bussy-Lettrée');
insert into city (id,code,name) values (15,'DAMP-TPL', 'Dampierre-au-Temple');
insert into city (id,code,name) values (16,'JUVIGNY', 'Juvigny');
insert into city (id,code,name) values (17,'MONCETZ', 'Moncetz-Longevas');
insert into city (id,code,name) values (18,'ST-ETIENNE', 'Saint-Etienne-au-Temple');
insert into city (id,code,name) values (19,'ST-GIBRIEN', 'Saint-Gibrien');
insert into city (id,code,name) values (20,'ST-HILAIRE', 'Saint-Hilaire-au-Temple');
insert into city (id,code,name) values (21,'VEUVE', 'La Veuve');
insert into city (id,code,name) values (22,'VRAUX', 'Vraux');

insert into district (id,code,name) values (1,'CENTRE', 'Centre');
insert into district (id,code,name) values (2,'CRX-DAMP', 'Croix Dampierre');
insert into district (id,code,name) values (3,'ST-ANTOINE', 'Faubourg Saint-Antoine - Madagascar');
insert into district (id,code,name) values (4,'LANG-LAFOR', 'Langevin - Laforest');
insert into district (id,code,name) values (5,'MT-HERY', 'Mont Héry');
insert into district (id,code,name) values (6,'MNT-ST-MIC', 'Mont Saint-Michel - Bidée');
insert into district (id,code,name) values (7,'ORAD-FRIS', 'Oradour - Frison - Gare');
insert into district (id,code,name) values (8,'SCHMIT', 'Schmit');
insert into district (id,code,name) values (9,'ST-PIERRE', 'Vallée Saint-Pierre');
insert into district (id,code,name) values (10,'VERBEAU', 'Verbeau');
insert into district (id,code,name) values (11,'FAGNIERES', 'Fagnières');
insert into district (id,code,name) values (12,'ST-MARTIN', 'Saint Martin-sur-le-Pré');
insert into district (id,code,name) values (13,'CONDE', 'Condé');
insert into district (id,code,name) values (14,'MATOUGUES', 'Matougues');
insert into district (id,code,name) values (15,'MOURM-LG', 'Mourmelon le Grand');
insert into district (id,code,name) values (16,'BACONNES', 'Baconnes');
insert into district (id,code,name) values (17,'GRD-LOGES', 'Les Grandes Loges');
insert into district (id,code,name) values (18,'SARRY', 'Sarry');
insert into district (id,code,name) values (19,'ST-MEMMIE', 'Saint-Memmie');
insert into district (id,code,name) values (20,'RECY', 'Recy');
insert into district (id,code,name) values (21,'COMPERTRIX', 'Compertrix');
insert into district (id,code,name) values (22,'COOLUS', 'Coolus');


INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (1, 'Lampe - Allumée de jour', 'EP', null, null, null);
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (2, 'Lampe - Décroc e', 'EP', 72, 72, null);
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (3, 'Lampe - Éteinte', 'EP', 72, 72, null);
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (4, 'Lampe - Clignote', 'EP', 72, 72, null);
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (5, 'Armoire - Accidentee / Vandalisee', 'EP', 1, 120, 48);
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (6, 'Armoire - Ouverte', 'EP', null, null, null);
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (7, 'Armoire au noir', 'EP', 2 , 24, 12 );
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (8, 'Rue Allumee de jour', 'EP', null, null, null);
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (9, 'Rue Dans le Noir (départ au noir)', 'EP', 24 , 24 , null);
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (10, 'Mise en valeur - Allumee de jour', 'EP', null, null, null);
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (11, 'Mise en valeur - Endommagée', 'EP', null, null, null);
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (12, 'Mise en valeur - Eteinte', 'EP', null, null, null);
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (13, 'Luminaire - Accidente menacant de tomber', 'EP', 1 , 120 , 48 );
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (14, 'Luminaire - Accidente sans menace', 'EP', 72, 72, null);
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (15, 'Luminaire - Flux lumineux occulte', 'EP', 72, 72, null);
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (16, 'Luminaire - Manquant', 'EP', 72, 72, null);
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (17, 'Vasque - Cassee / Ouverte / Manquante', 'EP', null, null, null);
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (18, 'Cable - a terre / accessible', 'EP', 1 , 120 , 48 );
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (19, 'Porte - Accidentee / Manquante', 'EP', null, null, null);
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (20, 'Support - Accidente', 'EP', 1 , 120 , 48 );
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (21, 'Support - Manquant', 'EP', null, null, null);
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (22, 'Plusieurs points lumineux consécutif en panne (au moins 3)', 'EP', 24 , 24 , null);
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (23, 'MANIFESTATION', 'PAT', null, null, null);
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (24, 'Réservation de salle', 'MANI', null, null, null);
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (25, 'Location de matériel', 'MANI', null, null, null);
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (26, 'Commémoration', 'MANI', null, null, null);
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (27, 'Livraison de matériel', 'MANI', null, null, null);
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (28, 'Festivité', 'MANI', null, null, null);
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (29, 'Exercice incendie', 'MANI', null, null, null);
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (30, 'Capteur au sol en panne', 'MOB', null, null, null);
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (31, 'Menuiserie', 'PAT', null, null, null);
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (32, 'Serrurerie', 'PAT', null, null, null);
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (33, 'Electricité', 'PAT', null, null, null);
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (34, 'Plomberie', 'PAT', null, null, null);
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (35, 'Maçonnerie', 'PAT', null, null, null);
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (36, 'Peinture', 'PAT', null, null, null);
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (37, 'Vitrerie', 'PAT', null, null, null);
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (38, 'Défaut VM Wifi', 'RT', 6 , 8 , null);
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (39, 'Borne WIFI en panne', 'RT', 6 , 12 , null);
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (40, 'Perte de signal Wifi', 'RT', 6 , 12 , null);
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (41, 'Borne WIFI accidentée / vandalisée', 'RT', 6 , 12 , null);
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (42, 'Zone Director en panne', 'RT', 6 , 12 , null);
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (43, 'Modem Wifi en panne', 'RT', 6 , 12 , null);
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (44, 'Switc Wifi en panne', 'RT', 6 , 12 , null);
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (45, 'Gateway Lora en panne', 'RT', 6 , 8 , null);
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (46, 'Perte de signal LORA', 'RT', 6 , 8 , null);
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (47, 'Serveur LNS en panne', 'RT', 6 , 8 , null);
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (48, 'Boite épissure défectueuse fibre (BPE)', 'RT', 6 , 8 , null);
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (49, 'Défaut fibre principale (144 à 48 FO)', 'RT', 6 , 8 , null);
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (50, 'Défaut fibre secondaire (24 à 6 FO)', 'RT', 6 , 8 , null);
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (51, 'Défaut C ambre / regard fibre', 'RT', null, null, null);
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (52, 'Feux clignotants', 'SLT', 24 , 24 , null);
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (53, 'Feu Orange ne fonctionne plus', 'SLT',  24 , 24 , null);
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (54, 'Feu Rouge ne fonctionne plus', 'SLT',  24 ,  24 , null);
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (55, 'Feu Vert ne fonctionne plus', 'SLT',  24 ,  24 , null);
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (56, 'Feu accidenté / Vandalisee', 'SLT', 1 , 1 , null);
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (57, 'Armoire en panne avec carrefour au noir', 'SLT', 1 , 1 , null);
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (58, 'Remonté de défaut contrôleur', 'SLT',  24 ,  24 , null);
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (59, 'Armoire - Accidentee / Vandalisee', 'SLT', 1 , 1 , null);
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (60, 'Détecteur ou boucle de détection', 'SLT', null, null, null);
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (61, 'Défaut routeur', 'SLT', null, null, null);
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (62, 'Défaut système priobus', 'SLT',  24 ,  24 , null);
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (63, 'Système priobus - Accidentee / Vandalisee', 'SLT',  24 ,  24 , null);
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (64, 'Perte de signal caméra', 'VP', 6 , 8 , 8 );
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (65, 'Caméra vandalisée', 'VP', 6 , 8 , 8 );
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (66, 'Caméra en panne', 'VP', 6 , 8 , null);
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (67, 'Convertisseur média en panne', 'VP', 6 , 8 , null);
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (68, 'Moniteur vidéo en panne', 'VP', 6 , 8 , null);
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (69, 'Seveur d''application logicielle en panne', 'VP', 6 , 8 , null);
INSERT INTO service_type (id, type, domain, gti, gtr, gtrp) VALUES (70, 'Onduleur en panne', 'VP', 6 , 8 , null);